Product Management
  ---
  tags:
    - Products

  /products:
    get:
      summary: Get all products
      description: Retrieve a list of all available products.
      responses:
        200:
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    category:
                      type: string
                    image:
                      type: string
                    new_price:
                      type: number
                      format: float
                    old_price:
                      type: number
                      format: float
        500:
          description: Internal server error

    post:
      summary: Create a new product
      description: Add a new product to the store.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                category:
                  type: string
                image:
                  type: string
                new_price:
                  type: number
                  format: float
                old_price:
                  type: number
                  format: float
      responses:
        201:
          description: Product created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      name:
                        type: string
                      category:
                        type: string
                      image:
                        type: string
                      new_price:
                        type: number
                        format: float
                      old_price:
                        type: number
                        format: float
        400:
          description: Invalid input data
        500:
          description: Internal server error

  /products/{product_id}:
    get:
      summary: Get a product by ID
      description: Retrieve a specific product by its ID.
      parameters:
        - name: product_id
          in: path
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Product retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  category:
                    type: string
                  image:
                    type: string
                  new_price:
                    type: number
                    format: float
                  old_price:
                    type: number
                    format: float
        404:
          description: Product not found
        500:
          description: Internal server error